[versions]
axion-release = "1.21.1"
checker-qual = "3.52.1"
derby = "10.17.1.0"
errorprone = "2.45.0"
errorprone-plugin = "4.3.0"
groovy = "5.0.3"
h2 = "2.4.240"
hsqldb = "2.7.4"
jackson = "2.20.1"
jspecify = "1.0.0"
junit = "6.0.1"
maven-publish = "0.35.0"
mockito = "5.21.0"
mssql-jdbc = "13.3.0.jre11-preview"
mysql-connector = "9.5.0"
neo4j-jdbc = "6.10.3"
nullaway = "0.12.15"
oracle-ojdbc = "23.26.0.0.0"
postgresql = "42.7.8"
slf4j = "2.0.17"
spock = "2.4-groovy-5.0"
spotless = "8.1.0"
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
spring-framework = "7.0.2"
testcontainers = "2.0.3"
version-catalog-update = "1.0.1"

[libraries]
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }
derby-client = { module = "org.apache.derby:derbyclient", version.ref = "derby" }
derby-embedded = { module = "org.apache.derby:derby", version.ref = "derby" }
derby-tools = { module = "org.apache.derby:derbytools", version.ref = "derby" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-refaster = { module = "com.google.errorprone:error_prone_refaster", version.ref = "errorprone" }
groovy = { module = "org.apache.groovy:groovy" }
groovy-bom = { module = "org.apache.groovy:groovy-bom", version.ref = "groovy" }
groovy-sql = { module = "org.apache.groovy:groovy-sql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssql-jdbc" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
neo4j-jdbc-full-bundle = { module = "org.neo4j:neo4j-jdbc-full-bundle", version.ref = "neo4j-jdbc" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
oracle-ojdbc17 = { module = "com.oracle.database.jdbc:ojdbc17", version.ref = "oracle-ojdbc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core" }
spock-spring = { module = "org.spockframework:spock-spring" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-framework" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-mssqlserver = { module = "org.testcontainers:testcontainers-mssqlserver" }
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql" }
testcontainers-neo4j = { module = "org.testcontainers:testcontainers-neo4j" }
testcontainers-oracle-free = { module = "org.testcontainers:testcontainers-oracle-free" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-spock = { module = "org.testcontainers:testcontainers-spock" }

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
